name: Cleanup old artifacts
on:
  schedule:
    - cron: '0 3 * * *' # every day at 03:00 UTC
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete artifacts older than RETENTION_DAYS (7)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RETENTION_DAYS: 30
          REPO: ${{ github.repository }}
        run: |
          # compute cutoff in ISO format (works on Linux; fallback for macOS included)
          if date -d "$RETENTION_DAYS days ago" >/dev/null 2>&1; then
            cutoff=$(date -d "$RETENTION_DAYS days ago" --utc +%Y-%m-%dT%H:%M:%SZ)
          else
            cutoff=$(date -v-"$RETENTION_DAYS"d -u +%Y-%m-%dT%H:%M:%SZ)
          fi

          page=1
          while true; do
            resp=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github+json" "https://api.github.com/repos/$REPO/actions/artifacts?per_page=100&page=$page")
            ids=$(echo "$resp" | jq -r --arg cutoff "$cutoff" '.artifacts[] | select(.created_at < $cutoff) | .id')
            [ -z "$ids" ] && break
            for id in $ids; do
              echo "Deleting artifact $id"
              curl -s -X DELETE -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github+json" "https://api.github.com/repos/$REPO/actions/artifacts/$id"
            done
            page=$((page+1))
          done
